language: node_js
node_js: "14"

cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: sh ${TRAVIS_BUILD_DIR}/deploy.sh
  on:
    branch: master
